### ISSUE TITLE
Checklist for 3.2.0

### ISSUE THREAD

**Issue by Deadlock989** [Deadlock989/IndustrialRevolution#456]
This is a checklist of what needs to happen to adapt to the new 2.0 base game version, and some other things I have wanted to change or remove for some time now but held off because they were breaking changes.

Re-writes / additions needed for base game API changes:

- [ ] Remove all references to recipe/technology difficulty
- [ ] Rendering API changes
- [ ] Recipe `catalyst_amount` changes
- [ ] Investigate new recipe `maximum_productivity` in scrapping loops
- [ ] Investigate new entity `custom_state_string`

Changes / additions:

- [ ] Replace rubber trees/wood with latex harvested by a forestry machine variant from any living tree
- [ ] Water electrolysis
- [ ] Reduce stone-gravel-silica ratios (1:1 stone to gravel?) and compensate in recipes
- [ ] Advanced steel production (blast/arc furnace) direct from ores
- [ ] Improve coolant loops
- [ ] Liquid fuel equipment grid generator(s)

Removals:

- [ ] 5x5 solars

**Comment by Deadlock989** [comment]
Having killed off valves, the [maximum pipeline extent](https://factorio.com/blog/post/fff-430) announced today for the new fluid system is another unwanted spanner in the works. Having to break up medium-distance pipelines with pumps is fine, _if you have pumps_. IR3 has a whole section of early gameplay literally built on piping steam around, but there are no steam-era pumps.

Solution 1: make steam-era pumps. This almost certainly isn't going to happen this decade as discussed previously (#152). Pumps are one of the most complex graphics specifications in the game, if not _the_ most. A fluid-powered mover of the same fluid is also clearly problematic for a 2x2 entity, so it would probably end up being void-powered, which means it could then be used to cheese regular iron pipes carrying steam as well. You could shave off 80% of the rendering required if you just omitted all the optional fluid wagon connector sprites, but I don't see any way of actually stopping them from trying to connect anyway.

Solution 2: the max pipeline length is accessible in the core utility constants: whack it up to 512 or more. That's 16 chunks in length, which should suffice for most players; steam-era kilobases will just have to have multiple and separate boiler arrays.

**Comment by Deadlock989** [comment]
Uncovered further issues with the new fluid system that make it almost impossible to proceed. I'm going to stop working on this for the time being and see what develops after the official release before I make any decisions.
